### ISSUE TITLE
Create prototypes of Callback News

### ISSUE THREAD

**Issue by iraidamercedes** [callback-demons/callback-news#18]
- [x]  Desktop design
- [x]  Mobile design

Deliverable: https://www.notion.so/iraida07/Adobe-XD-fd52ea3b00574aa188522080b5a8b3f8#e049587cb64043d19705fdfb1055c731

**Comment by GerardoMarquezC** [comment]
Prototipo inicial

![image](https://user-images.githubusercontent.com/40473845/82720596-79b3ef80-9c7a-11ea-90ab-4e22d32176dd.png)
